import os
import re
import time
import json
import requests
import urllib3
from dotenv import load_dotenv

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
load_dotenv()

SPLUNK_HOST = os.getenv("SPLUNK_HOST")
SPLUNK_PORT = os.getenv("SPLUNK_PORT")
SPLUNK_TOKEN = os.getenv("SPLUNK_TOKEN")

def test_connection():
    """Tests the connection to the Splunk Engine."""
    url = f"https://{SPLUNK_HOST}:{SPLUNK_PORT}/services/server/info?output_mode=json"
    headers = {"Authorization": f"Bearer {SPLUNK_TOKEN}"}
    try:
        response = requests.get(url, headers=headers, verify=False)
        if response.status_code == 200:
            return True, response.json()['entry'][0]['content']['version']
        return False, response.text
    except Exception as e:
        return False, str(e)

def push_config_to_splunk(ai_output_text):
    """(App 1) Parses AI text and pushes props.conf to Splunk."""
    unique_id = str(int(time.time()))[-5:]
    payload = {
        "name": f"prisme_agent_{unique_id}",
        "description": "Autonomously generated by Prisme AI Agent",
        "pulldown_type": "1"
    }
    
    time_format_match = re.search(r"TIME_FORMAT\s*=\s*(.+)", ai_output_text)
    if time_format_match: payload["TIME_FORMAT"] = time_format_match.group(1).strip()
    time_prefix_match = re.search(r"TIME_PREFIX\s*=\s*(.+)", ai_output_text)
    if time_prefix_match: payload["TIME_PREFIX"] = time_prefix_match.group(1).strip()
    max_lookahead_match = re.search(r"MAX_TIMESTAMP_LOOKAHEAD\s*=\s*(\d+)", ai_output_text)
    if max_lookahead_match: payload["MAX_TIMESTAMP_LOOKAHEAD"] = max_lookahead_match.group(1).strip()
    linemerge_match = re.search(r"SHOULD_LINEMERGE\s*=\s*(true|false)", ai_output_text, re.IGNORECASE)
    if linemerge_match: payload["SHOULD_LINEMERGE"] = linemerge_match.group(1).strip().lower()

    url = f"https://{SPLUNK_HOST}:{SPLUNK_PORT}/services/saved/sourcetypes?output_mode=json"
    headers = {"Authorization": f"Bearer {SPLUNK_TOKEN}"}
    try:
        response = requests.post(url, headers=headers, data=payload, verify=False)
        if response.status_code in [200, 201] or response.status_code == 409:
            return True, f"Successfully deployed config: '{payload['name']}'"
        return False, f"Splunk API Error: {response.text}"
    except Exception as e:
        return False, f"Connection Error: {str(e)}"

def push_dashboard_via_mcp(analysis_data):
    """(App 2) Builds an XML Dashboard from AI SPL queries and pushes it to Splunk."""
    unique_id = str(int(time.time()))[-5:]
    dashboard_name = f"prisme_code_insights_{unique_id}"
    
    xml_panels = ""
    for spl in analysis_data.get('spl_queries', []):
        xml_panels += f"""
        <row>
          <panel>
            <title>{spl['name']}</title>
            <chart>
              <search>
                <query><![CDATA[{spl['spl']}]]></query>
                <earliest>-24h@h</earliest>
                <latest>now</latest>
              </search>
            </chart>
          </panel>
        </row>
        """

    dashboard_xml = f"""<dashboard version="1.1">
      <label>Prisme Auto-Instrumentation: {dashboard_name}</label>
      <description>Autonomously generated from application codebase via Splunk Hosted AI.</description>
      {xml_panels}
    </dashboard>"""

    url = f"https://{SPLUNK_HOST}:{SPLUNK_PORT}/servicesNS/nobody/search/data/ui/views?output_mode=json"
    headers = {"Authorization": f"Bearer {SPLUNK_TOKEN}"}
    payload = {"name": dashboard_name, "eai:data": dashboard_xml}

    try:
        response = requests.post(url, headers=headers, data=payload, verify=False)
        if response.status_code in [200, 201] or response.status_code == 409:
            return True, f"Dashboard '{dashboard_name}' deployed to Splunk UI!"
        return False, f"Splunk API Error: {response.text}"
    except Exception as e:
        return False, f"Connection Error: {str(e)}"